@IsTest
public with sharing class ADO_PilelineClass_Test {
    public void ADO_PilelineClass_Test(){
        System.System.debug('ADO Pipeline');
        System.System.debug('ADO Pipeline');
        System.System.debug('ADO Pipeline');
        System.System.debug('ADO Pipeline');
        System.System.debug('ADO Pipeline');
        System.System.debug('ADO Pipeline');
        System.System.debug('ADO Pipeline');
        System.System.debug('ADO Pipeline');
        System.System.debug('ADO Pipeline');
    }
}